server:
  extraArgs:
    - --insecure

  rbacConfig:
    policy.csv: |
      p, nidgetgod, *, *, *, allow

  oidc:
    config: |
      name: authentik
      issuer: https://authentik.test.tixcraft.com/application/o/argocd/
      clientID: 5a59f50978edb2964ad312b457996cfee855ef96
      clientSecret: 0c622e658de88d148d3928e86d9f209051dcfda748595e102fa7a56923b0b3eca88b4841b96bb5b7b22a14efdb84c1f75f37d4175b388a19f9793f143a7955a0
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email
        - groups
      logoutURL: https://authentik.test.tixcraft.com/application/o/argocd/end-session/

  url: https://argocd-new.test.ticketmaster.sg

  service:
    type: NodePort
    nodePortHttp: 31080
    nodePortHttps: 31443

  ingress:
    enabled: true
    hosts:
      - argocd-new.test.ticketmaster.sg
    pathType: Prefix
    paths:
      - /
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-1:871038670252:certificate/6a2aee61-252f-45e6-920b-5e477ad4937e
      alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600
      alb.ingress.kubernetes.io/subnets: subnet-0ea76de587b0bee3b,subnet-00831cfa6a9cf1bbe
      alb.ingress.kubernetes.io/tags: Name=Test K8s,Resource Group=test,Organization=tmsg
      external-dns.alpha.kubernetes.io/target: aa1d451f988d9418dbf7b3637b228204-1533970775.us-west-1.elb.amazonaws.com

  route:
    enabled: false

  config:
    resource.customizations: |
      networking.k8s.io/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs
